services:
  - type: web
    name: food-delivery-backend
    env: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
